# Generated by Django 4.2.19 on 2025-03-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
