services:
  web:
    container_name: tracker-jacker-web
    build:
      context: ../frontend/
      dockerfile: ../frontend/Dockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: ../frontend/
        target: /home/node/app/
      - type: volume
        target: /home/node/app/node_modules
      - type: bind
        source: ../frontend/vite.config.ts
        target: /home/node/app/vite.config.ts
    environment:
      - VITE_BACKEND_URL=http://django-api:7004/
      - VITE_APP_NAME=Tracker Jacker
    ports:
      - 7001:5173
    depends_on:
      django-api:
        condition: service_healthy

  django-api:
    container_name: tracker-jacker-django-api
    build:
      context: ../backend/
      dockerfile: ../backend/Dockerfile
    ports:
      - 7004:7004
    volumes:
      - ../backend:/backend
    environment:
      - DEBUG=1
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=adminpassword
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py createsuperuser --noinput || true &&
             python manage.py runserver 0.0.0.0:7004"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7004/api/health/"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  db:
    image: mysql:8.2.0
    container_name: tracker-jacker-mysql
    ports:
      - 7003:3306
    environment:
      MYSQL_ROOT_PASSWORD: dbroot
      MYSQL_DATABASE: tracker_jacker
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - "tracker_jacker_db:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin
    container_name: tracker-jacker-phpmyadmin
    ports:
      - 7002:80
    environment:
      PMA_HOSTS: db
      UPLOAD_LIMIT: 50M

  nginx:
    image: nginx:latest
    container_name: tracker-jacker-nginx
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - web
      - django-api

volumes:
  tracker_jacker_db: {}